"""Glossary — English (2026-09-23). Same keys and structure as `sozluk.py`.

Written for a native English reader, not translated line by line: the
anchors are the same measured examples from this library (K13).
"""

from __future__ import annotations

SOZLUK_EN: dict[str, dict[str, str]] = {
    "stem": {
        "ad": "stem",
        "kisa": "A recording split down to a single instrument: the drum track, the bass track, the vocal track.",
        "nasil": "The Demucs (htdemucs) model splits a 30-second clip into four stems: drums, bass, other, vocals.",
        "capalar": "Guitar and keys can't be separated from each other; both land in `other`.",
        "uyari": "Separation isn't perfect; in a dense mix the stems bleed into each other. Read the numbers with that noise in mind.",
    },
    "izgara_entropi": {
        "ad": "grid entropy",
        "kisa": "How tightly the hits lock to the 16th-note grid. Low means machine, high means human hands.",
        "nasil": "Each hit on the drum stem is placed into one of 16 slots within the bar and the entropy of that spread is taken. A programmed beat piles into a few slots; a human spreads out.",
        "capalar": "Eminem 0.755 (programmed) · Meshuggah and Casiopea 0.99 (human). Library median 0.98.",
        "uyari": "Most of the library sits between 0.95 and 0.99; the measure does its work in the TAILS, and tells you little in the middle.",
    },
    "tekme_payi": {
        "ad": "kick share",
        "kisa": "How much of the drum sound comes from the kick.",
        "nasil": "Energy below 120 Hz on the drum stem, as a share of total drum energy.",
        "capalar": "Casiopea 0.17 (light foot) · TOOL 0.41 (tom-and-kick heavy). Library median 0.21.",
        "uyari": "kick + snare + cymbals ≈ 1. When one goes up another has to come down; don't read the three independently.",
    },
    "trampet_payi": {
        "ad": "snare share",
        "kisa": "How much of the drum sound comes from snare and toms.",
        "nasil": "Energy share between 120 and 2000 Hz on the drum stem.",
        "capalar": "Meshuggah 0.17 (stingy with the snare) · Eminem 0.45.",
        "uyari": "kick/snare/cymbals sum to ≈ 1 (compositional).",
    },
    "zil_payi": {
        "ad": "cymbal share",
        "kisa": "How much of the drum sound comes from the cymbals (ride, hi-hat, crash).",
        "nasil": "Energy share above 6000 Hz on the drum stem.",
        "capalar": "TOOL 0.17 (punchy, sparse cymbals) · Meshuggah 0.62 (ride-heavy) · Casiopea 0.52. Median 0.37.",
        "uyari": "kick/snare/cymbals sum to ≈ 1 (compositional).",
    },
    "nota_vurus": {
        "ad": "notes per beat",
        "kisa": "How many notes land on each beat: density, independent of tempo.",
        "nasil": "Detected note onsets divided by detected beats. Fast but sparse playing scores low; slow but busy playing scores high.",
        "capalar": "Eminem 1.51 · TOOL 1.96 · Casiopea 2.73 · Meshuggah 2.88.",
        "uyari": "",
    },
    "harmonik_pay": {
        "ad": "harmonic share",
        "kisa": "How much of the sound is regular and tonal versus noisy. Distortion pulls it down.",
        "nasil": "HPSS splits the harmonic and percussive parts; this is the share of harmonic energy.",
        "capalar": "Annihilator 0.77 (thrash, distorted) · A-Ha 0.97 (clean synth). Median on the `other` stem: 0.88.",
        "uyari": "It doesn't measure distortion directly, it measures noisiness. Three other candidates (spectral flatness, crest factor, spectral contrast) were tried for this job and dropped.",
    },
    "perde_medyan": {
        "ad": "pitch",
        "kisa": "The typical pitch on that stem: low or high.",
        "nasil": "The fundamental is tracked with the yin algorithm; the median is taken in semitones above C1. 0 = C1, 12 = C2, 24 = C3.",
        "capalar": "Bass stem ~9 (G1) · guitar/keys ~24 · vocals ~37.",
        "uyari": "Not measured on drums (no pitch).",
    },
    "perde_araligi": {
        "ad": "pitch range",
        "kisa": "How wide an area the melody moves around in.",
        "nasil": "The gap between the 90th and 10th percentile of measured pitches, in semitones.",
        "capalar": "Vocals: Panchiko 8.9 (flat delivery) · Death 37.8 (wide roaming). Median 26.",
        "uyari": "From a single 30-second clip; if it lands on a quiet part of the album, it comes out narrow.",
    },
    "vibrato_hizi": {
        "ad": "vibrato",
        "kisa": "How many times per second the pitch wavers. A straight singer scores low.",
        "nasil": "How often the pitch curve crosses its own moving average.",
        "capalar": "Median on vocals: 5.6 Hz.",
        "uyari": "",
    },
    "sustain_orani": {
        "ad": "sustain",
        "kisa": "How long a note rings after its attack. Staccato scores low, held notes high.",
        "nasil": "For each onset, the ratio of energy at the end of the window (up to the next note, max 300 ms) to the attack peak; median across notes.",
        "capalar": "April Wine drums 0.21 · Annihilator drums 0.94.",
        "uyari": "The first definition (share of frames above 20% of peak RMS) always gave 1.00 on sustained stems and was dropped.",
    },
    "parlaklik": {
        "ad": "brightness",
        "kisa": "How far toward the treble the sound's centre of gravity sits.",
        "nasil": "Spectral centroid, in Hz.",
        "capalar": "Bass ~260 Hz · guitar/keys ~1660 · drums ~3680 · vocals ~2450.",
        "uyari": "",
    },
    "dinamik_db": {
        "ad": "dynamics",
        "kisa": "The gap between the loudest and quietest moments.",
        "nasil": "Difference between the 95th and 5th percentile of RMS, in dB.",
        "capalar": "",
        "uyari": "Previews may be loudness-normalised; don't compare across sources.",
    },
    "enerji_payi": {
        "ad": "energy share",
        "kisa": "How much room that instrument takes up in the mix.",
        "nasil": "Stem energy as a share of total mix energy.",
        "capalar": "The four stems don't add up to 1: there's Demucs residue and overlap.",
        "uyari": "It depends on mixing decisions; it tells you about the production, not the playing.",
    },
    "eksen": {
        "ad": "axis",
        "kisa": "One of the taste directions pulled out of your library by fuzzy clustering. You name them.",
        "nasil": "Albums are clustered with fuzzy c-means (FCM) on a matrix built from credits, genre, scene and sound blocks.",
        "capalar": "An album can belong to more than one axis; a hard assignment would lose that.",
        "uyari": "12 clusters × 302 albums ≈ 25 per cluster. It's a coarse split; for a finer description look at the tags.",
    },
    "uyelik": {
        "ad": "membership",
        "kisa": "How strongly an album belongs to an axis (0–1).",
        "nasil": "The u_ij value FCM produces. An album's memberships across all axes add up to 1.",
        "capalar": "",
        "uyari": "",
    },
    "stabilite": {
        "ad": "stability (Jaccard)",
        "kisa": "If the clustering were redone, would this cluster land in the same place?",
        "nasil": "The clustering is repeated on bootstrap samples and the average Jaccard similarity of the clusters is taken. Threshold 0.60.",
        "capalar": "Unstable clusters can't be named: giving an identity to something that won't show up in the same place again would be wrong.",
        "uyari": "",
    },
    "ses_uzakligi": {
        "ad": "sound distance",
        "kisa": "How far a pick sits from the sound centre of the axis you chose, in library standard deviations.",
        "nasil": "Distance between the pick's stem measurements and the axis's median profile, scaled by the library's spread (normalised by the number of dimensions).",
        "capalar": "Reference points from your own albums: on the metal axis its own members sit at 0.76, rock clusters ~0.95, hip-hop 1.31.",
        "uyari": "It doesn't work on every axis. The sound centre of a mixed cluster doesn't mean much: on one axis its own members were 0.98 and the rest 1.01, so no separation. The page shows the baseline.",
    },
    "icra_profili": {
        "ad": "performance profile",
        "kisa": "HOW a musician plays: not their genre, not their production.",
        "nasil": "The median of the relevant stem measurements across the albums where the person plays that role.",
        "capalar": "A drummer's cymbal/kick balance, grid entropy and note density.",
        "uyari": "It rests on credit data; if someone has many roles and only a small share in this one, the profile may not represent them (the page warns you).",
    },
    "kredi_sicramasi": {
        "ad": "credit hop",
        "kisa": "Other work, that you haven't heard, by a musician from your library.",
        "nasil": "The musicians on an axis's lineup are found and their other records are looked up on Discogs.",
        "capalar": "\"Geddy Lee plays bass, guitar and synth on it. You have 13 albums he plays on.\"",
        "uyari": "Measured: a high discovery rate (it brings new things) but a low hit rate (1 of 3 decisions was a like).",
    },
    "sahne_komsulugu": {
        "ad": "scene neighbours",
        "kisa": "Artists played by people who play what you play: ONE step in the crowd graph.",
        "nasil": "ListenBrainz `similar-artists`: neighbours of the axis's artists, the ones several artists point to first.",
        "capalar": "",
        "uyari": "Measured: 80% of your decisions were \"already know it\". It matches your taste but doesn't DISCOVER anything; it brings the famous neighbour.",
    },
    "bilincli_uzaklik": {
        "ad": "deliberate distance",
        "kisa": "A neighbour of a neighbour, but not your direct neighbour: TWO steps in the crowd graph.",
        "nasil": "Step-one neighbours act as bridges and their neighbours are collected; bridges and anything you own are removed. Ranking is by AXIS SPECIFICITY: how many different axes' pools it appears in.",
        "capalar": "On the metal axis: Children of Bodom, Dark Tranquillity.",
        "uyari": "Ranking by bridge count slid into the mainstream: Coldplay showed up in the metal cluster. Specificity is the primary measure.",
    },
    "liste_birlikteligi": {
        "ad": "playlist co-occurrence",
        "kisa": "Songs that show up in the SAME playlists as yours. A stand-in for collaborative filtering when there's no user history.",
        "nasil": "Co-occurrence across playlists gathered from Deezer, with popularity removed via normalised PMI.",
        "capalar": "The Ocean ↔ Pineapple Thief · Vega ↔ TNK · Adam Nitti ↔ Nathan East.",
        "uyari": "Playlists carry CONTEXT as much as musical similarity: workout, chill, party, and language. Measured (2026-09-23): Sezen Aksu landed on the grunge axis next to Duman through just 3 shared lists, two of them catch-all personal mixes and one titled \"türkçe\". The signal said \"same language\", not \"same style\". Picks resting on 3 lists or fewer are now flagged as weak evidence.",
    },
    "loao": {
        "ad": "hide-an-artist test",
        "kisa": "ALL of an artist's albums are hidden from the library and the engine is asked: \"can you find this one?\"",
        "nasil": "Each of the 147 artists is hidden in turn. What's left is the library of someone who's never heard of that artist. We hide artists, not albums: hide an album and the artist is still in the library, the engine finds them through credits, and you'd say \"already know it\", which is exactly what we're trying to avoid.",
        "capalar": "hybrid reaches 123/147 artists · playlists alone 109 · sound alone 104 · lineup graph 55–81.",
        "uyari": "The result is a LOWER BOUND. We only have ground truth for the 147 artists you own; many picks ranked above the hidden one may be good recommendations too, and we can't measure that. So trust the COMPARISON between methods, not the absolute level. And note: this test rewards finding what you already own, which isn't the same as finding what you'll like. Your real decisions disagreed with it (see What we learned).",
    },
    "tavan": {
        "ad": "ceiling",
        "kisa": "Is the hidden artist even IN the pool that source looks at?",
        "nasil": "An artist who isn't in the pool can't be found. That's a coverage gap, not a ranking error. The two are reported separately.",
        "capalar": "hybrid 123/147 · playlists 109 · sound 104.",
        "uyari": "Mix them up and you invest in the wrong thing: fixing the ranking won't bring in an artist who isn't in the pool.",
    },
    "yuzdelik": {
        "ad": "percentile",
        "kisa": "The found artist's rank, divided by the size of the pool.",
        "nasil": "median rank / number of artists in the pool. Random retrieval scores 0.50; lower is better.",
        "capalar": "playlists 0.092 (5.4× better than random) · sound 0.347 (1.4× better).",
        "uyari": "ACROSS DIFFERENT POOL SIZES, THIS IS THE ONLY NUMBER YOU CAN COMPARE. Measured: when the pool grew from 2,163 to 4,183 embeddings, recall@50 dropped from 0.08 to 0.03, because the number of competitors doubled too. In the same run the percentile improved from 0.349 to 0.311.",
    },
    "melez": {
        "ad": "hybrid ranking",
        "kisa": "Merging the RANKS of two signals: playlist neighbourhood and sound similarity.",
        "nasil": "score(x) = Σ w/(60 + rank). Scores aren't added because their scales can't be compared (link strength −1…+1, sound ≈ −0.35…0). Playlists weigh 1, sound weighs 2: reversed on 2026-09-15 after your real decisions favoured sound.",
        "capalar": "A pick that's first on one list but missing from the other loses to one that's fiftieth on both: overlap is rewarded.",
        "uyari": "Its real gain is REACH, not ranking: 14 artists can only be reached through sound; the playlist signal never sees them. The two signals aren't always independent though: both can pick up language (see playlist co-occurrence).",
    },
    "pmi": {
        "ad": "link strength (npmi)",
        "kisa": "How much more often two artists appear in the same playlists than their individual frequencies would predict.",
        "nasil": "log( P(a,b) / (P(a)·P(b)) ), then divided by −log P(a,b) to squeeze it between −1 and +1. A famous artist is in every playlist, so their denominator grows and their score fades.",
        "capalar": "Close to +1: they're always seen together. Around 0: no more together than chance. Negative: they avoid each other.",
        "uyari": "The normalisation is essential. With raw PMI an artist in two lists outscored one in a hundred: a rarity bonus. Measured (147-artist leave-one-out): normalising lifted recall@50 from 0.07 to 0.14.",
    },
    "kesif_orani": {
        "ad": "discovery rate",
        "kisa": "Was the pick actually NEW to you?",
        "nasil": "1 − (number of \"already know it\" / total decisions).",
        "capalar": "scene neighbours 20% · credit hop 100%.",
        "uyari": "\"Already know it\" isn't a taste decision: it counts toward this rate but not toward the hit rate.",
    },
    "zevk_isabeti": {
        "ad": "hit rate",
        "kisa": "Of the picks that were new to you, the share you liked.",
        "nasil": "liked / (liked + passed). \"Already know it\" is left out: you didn't say whether you liked it.",
        "capalar": "scene neighbours 100%, but a 20% discovery rate: it finds things you love and already know.",
        "uyari": "",
    },
    "wilson": {
        "ad": "Wilson interval",
        "kisa": "The uncertainty band around a rate when the sample is small.",
        "nasil": "Wilson score interval (90%). The normal approximation gives zero width at p=0 or p=1 and claims certainty from a single observation.",
        "capalar": "1/1 = 100% and 80/80 = 100% are not the same number; the width of the band makes that visible.",
        "uyari": "",
    },
    "yayilim": {
        "ad": "spread",
        "kisa": "How wide a listener you are on a given axis.",
        "nasil": "(p95 − p5) / median.",
        "capalar": "Kick weight 1.53 (wide) · grid entropy 0.26 (narrow).",
        "uyari": "On a narrow axis, a pick that strays is a risky one.",
    },
}
